DROP VIEW IF EXISTS REGION_COORD, UNIV_REGION, KAISTDEP_HASTRACK, UNIV_REGION_DEPARTMENT, RESULT_VIEW;

CREATE VIEW REGION_COORD AS
SELECT RID, Region, KAIST_scholarship, IO_COORDINATOR.NAME, IO_COORDINATOR.Tel
FROM REGION JOIN IO_COORDINATOR ON REGION.CID = IO_COORDINATOR.CID;

CREATE VIEW UNIV_REGION AS
SELECT UID, UNIVERSITY.RID, UNIVERSITY.Region, UNIVERSITY.Name, Country_id, Language_id, 
Available_number, Undergraduate, Graduate
FROM REGION_COORD JOIN UNIVERSITY ON UNIVERSITY.RID = REGION_COORD.RID;

CREATE VIEW KAISTDEP_HASTRACK AS
SELECT UID, KAIST_DEPT.DID, KAIST_DEPT.Name
FROM KAIST_DEPT JOIN HAS_TRACK ON KAIST_DEPT.DID = HAS_TRACK.DID;

CREATE VIEW UNIV_REGION_DEPARTMENT AS
SELECT UNIV_REGION.UID, RID, UNIV_REGION.Name, Region, DID, KAISTDEP_HASTRACK.Name as Dept, Language_id, 
Available_number, Undergraduate, Graduate
FROM UNIV_REGION JOIN KAISTDEP_HASTRACK ON UNIV_REGION.UID = KAISTDEP_HASTRACK.UID;

CREATE VIEW RESULT_VIEW AS
SELECT RID, DID, Univ_name, Region, Dept, Language_id, Available_number, Undergraduate, 
Graduate, URL
FROM UNIV_REGION_DEPARTMENT JOIN FORMER_EXCHANGE ON UNIV_REGION_DEPARTMENT.UID = FORMER_EXCHANGE.UID;

/*
SELECT Name,
FROM RESULT_VIEW
WHERE DID == '' AND RID == ''
*/