CREATE VIEW REGION_COORD AS
SELECT RID, Region, KAIST_scholarship, CID, IO_COORDINATOR.NAME, IO_COORDINATOR.Tel, 
FROM REGION JOIN IO_COORDINATOR ON REGION.CID == IO_COORDINATOR.CID;

CREATE VIEW UNIV_REGION AS 
SELECT *
FROM REGION_COORD JOIN UNIVERSITY ON UNIVERSITY.RID == REGION.RID;

CREATE VIEW KAISTDEP_HASTRACK AS
SELECT UID, DID
FROM KAIST_DEPARTMENT JOIN HAS_TRACK ON KAIST_DEPARTMENT.DID == HAS_TRACK.DID;

CREATE VIEW UNIV_REGION_DEPARTMENT AS
SELECT *
FROM UNIV_REGION JOIN KAISTDEP_HASTRACK ON UNIV_REGION.UID == KAISTDEP_HASTRACK.UID;

CREATE VIEW RESULT_VIEW AS
SELECT *
FROM UNIV_REGION_DEPARTMENT JOIN FORMER_EXCHANGE ON UNIV_REGION_DEPARTMENT.UID == FORMER_EXCHANGE.UID;

// Select both region and department
SELECT Name, 
FROM RESULT_VIEW
WHERE DID == '' AND RID == ''