-- Database and tables construction
CREATE DATABASE IF NOT EXISTS cs360_HOEP;
USE cs360_HOEP;
CREATE TABLE IF NOT EXISTS UNIVERSITY (
	UID INT PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Country_id VARCHAR(5),
	Language_id VARCHAR(5),
	Available_number INT NOT NULL,
	Undergraduate INT NOT NULL,
	Graduate INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FORMER_EXCHANGE (
	UID INT NOT NULL,
	Name VARCHAR(30) PRIMARY KEY,
	Post_date Date NOT NULL,
	URL VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS KAIST_DEPT (
	DID INT PRIMARY KEY,
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS HAS_TRACK (
	UID INT,
	DID INT,
	Univ_track VARCHAR(100) NOT NULL,
	PRIMARY KEY(UID, DID)
);

CREATE TABLE IF NOT EXISTS IO_COORDINATOR (
	CID INT PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
	Position VARCHAR(100) NOT NULL,
	Tel VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS REGION (
	RID INT PRIMARY KEY,
	Region VARCHAR(30) NOT NULL,
	KAIST_scholarship INT NOT NULL,
	CID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS LANGUAGE_CERTIFICATE (
	UID INT,
	Type VARCHAR(10),
	Language_id VARCHAR(2),
	Requisite VARCHAR(5) NOT NULL,
	PRIMARY KEY (UID, Type, Language_id)
);

CREATE USER 'tester'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON cs360_HOEP.* TO 'tester'@'localhost';