-- Database and tables construction
CREATE DATABASE IF NOT EXISTS cs360_HOEP;
USE cs360_HOEP;
CREATE TABLE IF NOT EXISTS UNIVERSITY (
	UID INT PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Country_id VARCHAR(5),
	Language_id VARCHAR(5),
	Available_number INT NOT NULL,
	Undergraduate INT NOT NULL,
	Graduate INT NOT NULL,
	Region VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORMER_EXCHANGE (
	UID INT,
	Univ_name VARCHAR(100) NOT NULL,
	Name VARCHAR(30),
	Post_date Date NOT NULL,
	URL VARCHAR(500) NOT NULL,
	PRIMARY KEY(UID, Name)
);

CREATE TABLE IF NOT EXISTS KAIST_DEPT (
	DID INT PRIMARY KEY,
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS HAS_TRACK (
	UID INT,
	Univ_name VARCHAR(100) NOT NULL,
	DID INT,
	KAIST_dept VARCHAR(100) NOT NULL,
	Univ_track VARCHAR(100) NOT NULL,
	PRIMARY KEY(UID, DID, Univ_track)
);

CREATE TABLE IF NOT EXISTS IO_COORDINATOR (
	CID INT PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
	Position VARCHAR(100) NOT NULL,
	Tel VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS REGION (
	RID INT PRIMARY KEY,
	Region VARCHAR(30) NOT NULL,
	KAIST_scholarship INT NOT NULL,
	CID INT NOT NULL,
	IO_Cname VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS LANGUAGE_CERTIFICATE (
	UID INT,
	Univ_name VARCHAR(100) NOT NULL,
	Type VARCHAR(10),
	Language_id VARCHAR(2),
	Requisite VARCHAR(5) NOT NULL,
	PRIMARY KEY (UID, Type, Language_id)
);

LOAD DATA INFILE 'C:/CS360-HOEP-Project/csv_data/UNIVERSITY.csv'
INTO TABLE UNIVERSITY
FIELDS TERMINATED BY ','
ignore 1 lines;

LOAD DATA INFILE 'C:/CS360-HOEP-Project/csv_data/FORMER_EXCHANGE.csv'
INTO TABLE FORMER_EXCHANGE
FIELDS TERMINATED BY ','
ignore 1 lines;

LOAD DATA INFILE 'C:/CS360-HOEP-Project/csv_data/KAIST_DEPT.csv'
INTO TABLE KAIST_DEPT
FIELDS TERMINATED BY ','
ignore 1 lines;

LOAD DATA INFILE 'C:/CS360-HOEP-Project/csv_data/HAS_TRACK.csv'
INTO TABLE HAS_TRACK
FIELDS TERMINATED BY ','
ignore 1 lines;

LOAD DATA INFILE 'C:/CS360-HOEP-Project/csv_data/IO_COORDINATOR.csv'
INTO TABLE IO_COORDINATOR
FIELDS TERMINATED BY ','
ignore 1 lines;

LOAD DATA INFILE 'C:/CS360-HOEP-Project/csv_data/REGION.csv'
INTO TABLE REGION
FIELDS TERMINATED BY ','
ignore 1 lines;

LOAD DATA INFILE 'C:/CS360-HOEP-Project/csv_data/LANGUAGE_CERTIFICATE.csv'
INTO TABLE LANGUAGE_CERTIFICATE
FIELDS TERMINATED BY ','
ignore 1 lines;

CREATE USER 'tester'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON cs360_HOEP.* TO 'tester'@'localhost';